#162948794 set an empty react app
andela/ah-django-unchained-frontend pull request #1
Opened 2019-02-06 16:48 UTC by Georgeygigz

**What does this PR do?**
- It creates a new react application

**Description of Task to be completed?**
- Creating a new application using `*npm create-react-app .`

**How should this be manually tested?**
- clone this repo `https://github.com/andela/ah-django-unchained-frontend`
- `cd ah-django-unchained-frontend`
- Install the required dependencies `npm install`
- `npm start to run the local server`
- The following message show that your server has been started successfully
 ``` 
You can now view ah-django-unchained-frontend in the browser.
  Local:            http://localhost:3004/
  On Your Network:  http://10.6.54.151:3004/

Note that the development build is not optimized.
To create a production build, use npm run build. 
```
**Pivotal Tracker story**

[#162948794](https://www.pivotaltracker.com/story/show/162948794)

2019-02-06 17:32 UTC, cosmas28 commented
@Georgeygigz kindly add linting using Airbnb eslint style guide as indicated in the chore description. Linting provides an extra measure of code quality by analyzing code and highlighting potential errors. It can also ensure consistency across projects with multiple developers.

2019-02-06 17:34 UTC, cosmas28 requested changes

2019-02-06 17:34 UTC, cosmas28 commented on package.json
> +  "scripts": {
Kindly add appropriate linting scripts.

2019-02-06 17:38 UTC, Georgeygigz commented on package.json
> +  "scripts": {
Okay noted

2019-02-06 18:09 UTC, cosmas28 commented
@Georgeygigz Good job for adding linters. However, I requested earlier that you should add scripts for running ESlint against the code directory and  Fixing eslint errors automatically.

2019-02-07 07:31 UTC, cosmas28 commented
Good improvement @Georgeygigz , one more thing before I merge this PR. Please run ESlint against our code directory and fix the eslint errors. e.g change the `App.js` to `App.jsx` because we are using JXS.

2019-02-07 08:27 UTC, cosmas28 approved these changes

2019-02-07 08:29 UTC, merged