#162948803 Create Reusable Components
andela/ah-django-unchained-frontend pull request #12
Opened 2019-02-14 09:31 UTC by KMaina

#### What does this PR do?
Create a reusable button and input box to be reused in other components
#### Description of Task to be completed?

Generate a button that allows a user to pass in
- the type
- CSS styles
- name of the button to be rendered

Generate an input box that allows a user to pass in

- the type of the input
- CSS styles
- the name of the input
- the id of the input
- any placeholder text

2019-02-14 18:21 UTC, cosmas28 commented
Kindly fix the failing tests on Travis

2019-02-14 19:10 UTC, cosmas28 requested changes

2019-02-14 19:10 UTC, cosmas28 commented on src/components/Button/button.test.jsx
> +  it('should render correctly', () => {
leave a space before an `it` block. This will make your code more readable.

2019-02-14 19:10 UTC, cosmas28 commented on src/components/Button/button.test.jsx
> +import React from 'react';
The name of a component test file should be the same to the name of its component.

2019-02-15 08:04 UTC, KMaina commented on src/components/Button/button.test.jsx
> +  it('should render correctly', () => {
Added a space

2019-02-15 08:04 UTC, KMaina commented on src/components/Button/button.test.jsx
> +import React from 'react';
Changed

2019-02-15 08:17 UTC, cosmas28 commented on .travis.yml
> +  - npm test -- -u
I love this...keep the initiative on top.

2019-02-15 08:31 UTC, cosmas28 requested changes

2019-02-15 08:31 UTC, cosmas28 commented on src/components/InputBox/Inputbox.test.jsx
> +import React from 'react';
The name of this test file does not match the name of the component.

2019-02-15 11:05 UTC, andrewhingah approved these changes

2019-02-15 11:07 UTC, cosmas28 approved these changes

2019-02-15 11:17 UTC, merged