#162948805 Add a user interface for profiles
andela/ah-django-unchained-frontend pull request #13
Opened 2019-02-14 22:58 UTC by SelaDanti

### What does this PR do?
Creates a user interface for profiles

### Description of tasks accomplished
- Created the user interface for creating profiles

### How this app should be tested?
clone this repo and checkout to ft-user-profile-axios-162948805
. install package requirement and run npm start to run the app

### Related pivotal tracker stories
[#162948805](https://www.pivotaltracker.com/story/show/162948805)

### Screenshots
<img width="1280" alt="screenshot 2019-02-15 at 01 56 49" src="https://user-images.githubusercontent.com/30651751/52823198-20e3c780-30c5-11e9-8d61-3f74a82b0773.png">

2019-02-26 07:22 UTC, andrewhingah commented
Hey @SelaDanti The title of this PR is misleading. This PR is not only about UI. Please make it more descriptive.

2019-02-26 07:23 UTC, andrewhingah commented
Please rebase your branch.

2019-02-26 07:25 UTC, andrewhingah commented on src/store/modules/profile/index.js
> +
Please remove this extra blank line

2019-02-26 08:32 UTC, andrewhingah commented on src/store/modules/profile/index.js
> +
Kindly go through this file again and remove all the unnecessary blank lines.

2019-02-26 09:00 UTC, d-kahara submitted a review, later dismissed

2019-02-26 09:00 UTC, d-kahara commented on package.json
> +    "bootstrap": "^4.3.0",
Any reason why you decided to use an older version bootstrap?

2019-02-26 09:00 UTC, d-kahara commented on src/components/InputBox/index.jsx
> +export default InputBox;
please add an extra line here

2019-02-26 09:00 UTC, d-kahara commented on src/components/ProfileImage/ProfileImage.test.jsx
> +describe ('ProfileImage', () => {
Consider changing indentation to 2 spaces in this file

2019-02-26 09:00 UTC, d-kahara commented on src/components/ProfileImage/index.jsx
> +          {console.log(message)}
please remove console message

2019-02-26 09:00 UTC, d-kahara commented on src/store/modules/profile/index.js
> +      console.log('>>>>>>>>>url!!!', res.data.secure_url);
Please remove console statement

2019-02-26 09:12 UTC, d-kahara commented on src/store/modules/signup/index.js
> +export default signUpReducer;
Please add an extra line here

2019-02-26 11:17 UTC, KMaina commented on src/components/ProfileForm/ProfileForm.test.jsx
> +  it('should call profileUpdateDispatch  on calling updateProfile', () => {
why are there 2 spaces between `profileUpdateDispatch` and  `on`

2019-02-26 11:36 UTC, KMaina commented on src/components/ProfileView/index.jsx
> +);
Please indent this closing bracket by 2 spaces

2019-02-26 11:37 UTC, KMaina commented on src/pages/Profile/Profile.test.jsx
> +      wrapper = shallow(<Profile />);
Kindly remove 2 indents from this line

2019-02-26 11:37 UTC, KMaina commented on src/pages/Profile/Profile.test.jsx
> +      expect(wrapper).toMatchSnapshot();
Kindly remove 2 indents from this line

2019-02-26 11:40 UTC, KMaina commented on src/store/modules/profile/index.js
> +import axios from 'axios';
If `axios` is not in use kindly remove it

2019-02-26 11:41 UTC, KMaina commented on src/store/modules/profile/index.js
> +const failprofileAction = payload => (
Kindly capitalize the p in `profile` to ensure you adhere to camelcase

2019-02-26 11:45 UTC, SelaDanti commented on package.json
> +    "bootstrap": "^4.3.0",
I have changed it to 4.3.1

2019-02-26 11:51 UTC, SelaDanti commented on src/store/modules/profile/index.js
> +import axios from 'axios';
Am using it in line 63

2019-02-26 14:00 UTC, cosmas28 commented on src/store/modules/profile/index.js
> +const getProfileRequest = payload => (
I like the way you named this action creator.

2019-02-26 14:25 UTC, cosmas28 requested changes

2019-02-26 14:25 UTC, cosmas28 commented on src/store/modules/profile/index.js
> +const failprofileFail = payload => (
Kindly correct this action name, you can sync with the other guys to help you.

2019-02-26 14:25 UTC, cosmas28 commented on src/store/modules/profile/index.js
> +export const profileRequestDispatch = user => dispatch => {
- Its not necessary to add the `Dispatch` prefix, kindly refer to what others are doing so that our codebase can be consistent.

2019-02-26 14:25 UTC, cosmas28 commented on src/store/modules/profile/index.js
> +const getProfileRequest = payload => (
I think this function should have a `success` prefix instead of `request`. Also, sync with others to know the meaning of the `Request` prefix.

2019-02-26 14:25 UTC, cosmas28 commented on src/store/modules/profile/index.js
> +export const profileUpdateDispatch = (user, data) => dispatch => {
It's a good practice to start the function names with a verb, ie, `updateProfile` instead `profileUpdateDispatch`.

2019-02-26 14:25 UTC, cosmas28 commented on src/store/modules/profile/type.js
> +export const REQUEST_PROFILE = 'REQUEST_PROFILE';
These action type names are do follow the right naming convention. Kindly sync with your teammates to refactor them.

2019-02-26 14:38 UTC, SelaDanti commented on src/store/modules/profile/type.js
> +export const REQUEST_PROFILE = 'REQUEST_PROFILE';
will do so

2019-02-27 09:47 UTC, Georgeygigz commented on src/components/ProfileForm/ProfileForm.css
> +.label
Kindly consider using two space indentation

2019-02-27 09:52 UTC, Georgeygigz commented on src/components/ProfileImage/ProfileImage.css
> +.profile-view
consider using two space indentation.

2019-02-27 09:58 UTC, Georgeygigz commented on src/components/ProfileView/index.jsx
> +import React, { Component } from 'react';
Container components should be located in `pages folder`

2019-02-27 10:50 UTC, Georgeygigz commented on src/store/modules/profile/index.js
> +export const profileRequest = user => dispatch => {
function name should be a `verb` consider renaming this function to `getProfile`

2019-02-27 10:50 UTC, Georgeygigz commented on src/store/modules/profile/index.js
> +export const profileUpdate = (user, data) => dispatch => {
consider renaming this too

2019-02-27 10:50 UTC, Georgeygigz commented on src/utils/helpers/http.js
>  import axios from 'axios';
consider using two space indentation.

2019-02-27 13:10 UTC, cosmas28 commented
Rebase and fix merge conflicts

2019-03-04 07:54 UTC, cosmas28 approved these changes

2019-03-04 07:55 UTC, merged