#162948802  reset password
andela/ah-django-unchained-frontend pull request #14
Opened 2019-02-15 10:15 UTC by MaggieChege

### What does this PR do?
User should be able to reset password

### Description of tasks accomplished
* Create UI for user update password 
* User receives email

### How this app should be tested?
clone this repo and checkout to ft-reset-password-162948802
. install package requirement and run npm start to run the app

Screenshots
![image](https://user-images.githubusercontent.com/18655501/52850094-bca42080-3123-11e9-876b-35d04241f9f9.png)
![image](https://user-images.githubusercontent.com/18655501/52850121-c62d8880-3123-11e9-8156-67223d714b3e.png)

### Related pivotal tracker stories
[#162948802](https://www.pivotaltracker.com/story/show/162948802)

2019-02-19 20:15 UTC, cosmas28 requested changes

2019-02-19 20:15 UTC, cosmas28 commented on src/pages/Passswordreset/UpdatePassword.jsx
> +        password: '',
Kindly use 2 spaces in indentation, go through every file changed and correct this.

2019-02-19 20:15 UTC, cosmas28 commented on src/pages/Passswordreset/UpdatePassword.jsx
> +        confirm_password: '',
Its a good practice to use camelCase is Js, so change `confirm_password` to `confirmPassword`, `passmismatch` to `passMisMatch`

2019-02-19 20:15 UTC, cosmas28 commented on src/pages/Passswordreset/UpdatePassword.test.jsx
> +
Also, go through your code and remove all unnecessary line spaces like this one.

2019-02-19 20:15 UTC, cosmas28 commented on src/pages/Passswordreset/index.jsx
> +    handleChange =(e) =>{
indent this and leave a line space before `handleChange` handler.

2019-02-19 20:15 UTC, cosmas28 commented
Kindly rebase

2019-02-19 20:25 UTC, MaggieChege commented on src/pages/Passswordreset/UpdatePassword.jsx
> +        password: '',
working on this right away.

2019-02-20 09:24 UTC, cosmas28 requested changes

2019-02-20 09:24 UTC, cosmas28 commented on src/routes/Routes.jsx
> +          <Route path='/users/passwordreset/' component={Resetpassword} />
kindly refactor this path to enable navigation from one component to another.i.e use `passwordreset` instead of `/users/passwordreset/`. Please refer [here](https://blog.pshrmn.com/entry/simple-react-router-v4-tutorial/)

2019-02-20 09:43 UTC, cosmas28 requested changes

2019-02-20 09:43 UTC, cosmas28 commented on src/pages/Passswordreset/UpdatePassword.jsx
> +export class UpdatePassword extends React.Component{
KIndly fix the indentation in this component.

2019-02-20 09:43 UTC, cosmas28 commented on src/pages/Passswordreset/UpdatePassword.test.jsx
> +    const state = {
indentation here too.

2019-02-20 09:43 UTC, cosmas28 commented on src/pages/Passswordreset/index.jsx
> +        state = {email: ''};
indentation here too.

2019-02-20 09:43 UTC, cosmas28 commented on src/pages/Passswordreset/reset.scss
> +
Kindly go through all the files here and remove these empty lines.

2019-02-21 15:01 UTC, cosmas28 approved these changes

2019-02-21 15:15 UTC, merged