#162948801 Ft registration (implement redux config)
andela/ah-django-unchained-frontend pull request #15
Opened 2019-02-15 10:54 UTC by d-kahara

#### What does this PR do?
Creates a user Interface through which a user can be able to register and create an account.

#### Description of Task to be completed?
* [x]  Create a folder structure
* [x]  Create React components,views
* [x]  Configure Redux and saga middleware
* [x]  Consume the Register API endpoint
* [ ]  Add Tests

#### How should this be manually tested?
1. Clone this repository on your local machine using
   `git clone https://github.com/andela/ah-django-unchained-frontend.git`
2. Change your working directory to the project's directory using
   `cd ah-django-unchained-frontend`
3. Change to the specific branch `ft-registration-redux-162948801` using
   `git checkout ft-registration-redux-162948801`
4. Run `npm install` to install all the modules listed in the `package.json` file.
5. Run `npm start` command to start the application.
6. The application should start successfully. On the browser, navigate to the URL `http://localhost:3000/signup`, .

2019-02-16 13:32 UTC, cosmas28 commented
- Fix merge conflicts and Travis errors
- Stash your commit messages into one because their `<header>` are the same.

2019-02-16 13:37 UTC, cosmas28 requested changes

2019-02-16 13:37 UTC, cosmas28 commented on src/utils/helpers/http.js
> +
remove one line here.

2019-02-16 13:37 UTC, cosmas28 commented on src/store/modules/signup/index.js
> +
remove one line space here.

2019-02-16 13:41 UTC, cosmas28 requested changes

2019-02-16 13:41 UTC, cosmas28 commented on src/pages/Signup/index.jsx
> +  isFetching: state.signUpReducer.isFetching,
use destructuring here to avoid repetition of the `state.signUpReducer`.

2019-02-16 13:41 UTC, cosmas28 commented on src/pages/Signup/index.jsx
> +
there should one line space only before any function.

2019-02-16 13:41 UTC, cosmas28 commented on src/pages/Signup/index.jsx
> +
leave one line space only here.

2019-02-19 03:01 UTC, cosmas28 commented
Any reason why the PR description does not have `The PT Story link`?

2019-02-19 03:04 UTC, cosmas28 commented
Your commit messages are clear and concise, however, you should avoid using `Delivers` in the `<Footer>`. This is because Delivering the stories is the work of our stakeholders. So kindly use `Finishes`.

2019-02-19 03:27 UTC, cosmas28 requested changes

2019-02-19 03:27 UTC, cosmas28 commented on .eslintrc
> +      "react/jsx-wrap-multilines": 0,
Any reason why you are switching off these rules?

2019-02-19 03:27 UTC, cosmas28 commented on src/components/InputBox/index.jsx
> +  const { type, className, name, id, placeholder, onChange, required } = props;
Good work here, keep it up.

2019-02-19 03:27 UTC, cosmas28 commented on src/pages/SignupPage/SignupPage.test.js
> +  it('should render the signup route', () => {
the format of this title is TIA though the assertion is testing something different.

2019-02-19 03:27 UTC, cosmas28 commented on src/pages/SignupPage/SignupPage.test.js
> +
Kindly add a snapshot test, it's a good practice to have a snapshot test for every component.

2019-02-19 03:27 UTC, cosmas28 commented on src/pages/SignupPage/index.jsx
> +    const { errors, isFetching } = this.props;
This is a good approach though it is creating some repetition, so to avoid repetition, remove this line and add the `errors, isFetching` to line 30.

2019-02-19 03:27 UTC, cosmas28 commented on src/pages/SignupPage/index.jsx
> +
remove this one line space here, also at line 67.

2019-02-19 03:27 UTC, cosmas28 commented on src/pages/SignupPage/index.jsx
> +  success: PropTypes.bool.isRequired
Kindly use a more descriptive prop name other than `success`, ie, `successMessage`.

2019-02-19 03:27 UTC, cosmas28 commented on src/routes/Routes.jsx
> +      <div>
Its a good practice in react to use `<React.Fragment></React.Fragment>` instead of an empty `<div>`. [React.Fragment](https://reactjs.org/docs/fragments.html)

2019-02-19 03:27 UTC, cosmas28 commented on src/store/modules/signup/signup.actions.test.js
> +
remove this line space.

2019-02-19 03:27 UTC, cosmas28 commented on src/store/modules/signup/signup.actions.test.js
> +
remove this line space here.

2019-02-19 03:27 UTC, cosmas28 commented on src/store/modules/signup/signup.actions.test.js
> +    afterEach(() => {
kindly leave a line space before every block of code, e.g `beforeEach`, `it` and `describe` blocks.

2019-02-19 03:27 UTC, cosmas28 commented on src/store/modules/signup/signup.actions.test.js
> +    it('should post user details after successfull HTTP call', () => {
Your indentation is not consistent. Kindly configure your VsCode to use 2 spaces.

2019-02-19 04:10 UTC, d-kahara commented on src/pages/SignupPage/SignupPage.test.js
> +
noted

2019-02-19 04:16 UTC, d-kahara commented
> Any reason why the PR description does not have `The PT Story link`?

Resolved

2019-02-19 04:20 UTC, d-kahara commented
> Your commit messages are clear and concise, however, you should avoid using `Delivers` in the `<Footer>`. This is because Delivering the stories is the work of our stakeholders. So kindly use `Finishes`.

Noted

2019-02-19 04:22 UTC, d-kahara commented on .eslintrc
> +      "react/jsx-wrap-multilines": 0,
They were causing unnecessary linting issues

2019-02-19 14:09 UTC, cosmas28 requested changes

2019-02-19 14:09 UTC, cosmas28 commented on src/store/modules/signup/signup.actions.test.js
> +		moxios.install();
Kindly correct the indentation in this file, make it 2 spaces.

2019-02-19 14:09 UTC, cosmas28 commented on src/store/modules/signup/signup.reducers.test.js
> +	it('should return the initial state', () => {
Kindly correct the identation in this file.

2019-02-19 14:09 UTC, cosmas28 commented on src/utils/helpers/testHelpers.js
> +
remove this line

2019-02-19 17:37 UTC, SelaDanti commented
Please state packages you have installed in the PR

2019-02-19 20:00 UTC, cosmas28 approved these changes

2019-02-19 20:01 UTC, merged