#162948804 Social authentication
andela/ah-django-unchained-frontend pull request #17
Opened 2019-02-16 12:12 UTC by Georgeygigz

**What does this PR do?**

* It adds social auth functionality

**Description of Task to be completed?**

* ASocial auth functionality
*  Add social auth buttons on sign up page.

**How should this be manually tested?**

* clone this repo `https://github.com/andela/ah-django-unchained-frontend`
* `cd ah-django-unchained-frontend`
* `git checkout ft-social-authentication-162948804`
* Install the required dependencies `npm install`
* `npm start to run the local server`

**Pivotal Tracker story**
[#162948804](https://www.pivotaltracker.com/story/show/162948804)
![image](https://user-images.githubusercontent.com/24627269/52899572-8a1a2680-31fc-11e9-966e-71d157ef739f.png)

2019-02-20 14:35 UTC, cosmas28 commented on src/store/modules/socialauth/index.js
> +export const GoogleAuth = data => {
change to `googleAuth`.

2019-02-20 14:36 UTC, cosmas28 commented on src/store/modules/socialauth/index.js
> +export const receivedUsers = action => ({
change to `authenticateUserSuccess`

2019-02-20 14:36 UTC, cosmas28 commented on src/store/modules/socialauth/types.js
> +export const GOOGLE = 'GOOGLE_ACCESS_CODE';
should be `GOOGLE_ACCESS_CODE_SUCCESS`

2019-02-20 14:54 UTC, cosmas28 requested changes

2019-02-20 14:54 UTC, cosmas28 commented on src/store/modules/socialauth/index.js
> +export const getError = error => ({
should be `authenticateUserFailed`

2019-02-20 14:54 UTC, cosmas28 commented on src/store/modules/socialauth/index.js
> +export default function SocialAuthReducer(state = initialState, action) {
use arrow functions.

2019-02-20 14:54 UTC, cosmas28 commented on src/store/modules/socialauth/index.js
> +export const fetchUsers = () => ({
should be `authenticateUserRequest`

2019-02-20 14:54 UTC, cosmas28 commented on src/store/modules/socialauth/__tests__/socialauth.reducer.test.js
> +import socialAuthReducer from '../index';
move this test file to `./modules/socialAuth`

2019-02-20 14:54 UTC, cosmas28 commented on src/routes/Routes.jsx
> +          <Route exact path="/" component={Home} />
change back to single quote

2019-02-20 14:54 UTC, cosmas28 commented on src/pages/socialauth/SocialAuth.jsx
> +import React from 'react';
change this file name and directory to `/pages/SocialAuth/index.jsx`

2019-02-20 14:54 UTC, cosmas28 commented on src/pages/socialauth/SocialAuth.jsx
> +export class SocialLoginComponent extends React.Component {
the component name should be `SocialAuth`.

2019-02-20 14:54 UTC, cosmas28 commented on src/pages/socialauth/SocialAuth.jsx
> +        button_class: 'google',
it's a good practice to use camelCase to name functions, variables and object's property.

2019-02-20 14:54 UTC, cosmas28 commented on src/pages/socialauth/SocialAuth.jsx
> +  socialAuthButton = providers => (
this name should be `renderSocialAuthButton`.

2019-02-20 14:54 UTC, cosmas28 commented on src/pages/socialauth/__tests__/Botton.test.jsx
> +  it('should be defined', () => {
not necessary

2019-02-20 14:54 UTC, cosmas28 commented on src/pages/socialauth/__tests__/SocialAuth.test.jsx
> +describe('Social Auth', () => {
the title should be `SocialAuth`

2019-02-20 14:54 UTC, cosmas28 commented on src/pages/socialauth/__tests__/SocialAuth.test.jsx
> +  describe('Login Component snapshot', () => {
remove this describe block and move the `it` block to the `describe` block below.

2019-02-20 15:45 UTC, Georgeygigz commented on src/pages/socialauth/SocialAuth.jsx
> +        button_class: 'google',
@cosmas28 , this name should be as it is because google provider should be named as I have named above

2019-02-21 06:41 UTC, cosmas28 approved these changes

2019-02-21 06:42 UTC, merged