#162948801 Create a loading component
andela/ah-django-unchained-frontend pull request #18
Opened 2019-02-17 13:47 UTC by d-kahara

#### What does this PR do?
Create a reusable loader component

#### Description of Task to be completed?
Generate a component that will be used throughout the app to show when app is loading data from the server or when performing an operation.

####Screenshots
<img width="1436" alt="screenshot 2019-02-17 at 16 46 29" src="https://user-images.githubusercontent.com/27801956/52913923-a5a43080-32d3-11e9-9cec-76a707f13b42.png">

2019-02-17 14:06 UTC, andrewhingah commented on src/components/Loader/index.jsx
> +
Remove these blank lines.

2019-02-17 15:48 UTC, cosmas28 requested changes

2019-02-17 15:48 UTC, cosmas28 commented on src/components/Loader/Loader.test.jsx
> +  it('should be defined', () => {
Kindly remove this test and use snapshot testing. We need to hit 100%.

2019-02-17 15:52 UTC, cosmas28 commented
Any reason for not having a Feature story for this PR?

2019-02-18 05:00 UTC, d-kahara commented
> Any reason for not having a Feature story for this PR?

Added this as a task under the signup feature story

2019-02-18 05:54 UTC, cosmas28 approved these changes

2019-02-18 05:55 UTC, merged