#162948806 All and single article UI
andela/ah-django-unchained-frontend pull request #19
Opened 2019-02-19 10:50 UTC by SelaDanti

### What does this PR do?
Creates a user interface for profiles

### Description of tasks accomplished
- Created the user interface for creating viewing multiple articles
- Created the user interface for creating viewing single articles

### How this app should be tested?
clone this repo and checkout to ft-fetch-all-articles-162948805
. install package requirement and run npm start to run the app

### Related pivotal tracker stories
[#162948806](https://www.pivotaltracker.com/story/show/162948806)

### Screenshots
<img width="1280" alt="screenshot 2019-02-19 at 13 49 01" src="https://user-images.githubusercontent.com/30651751/53009715-29cdf380-344d-11e9-8516-7b8e8f82de7d.png">

<img width="1280" alt="screenshot 2019-02-19 at 13 49 12" src="https://user-images.githubusercontent.com/30651751/53009738-33575b80-344d-11e9-8b63-1586cb2a01ba.png">

2019-02-19 12:25 UTC, andrewhingah commented
Kindly review your PR description. For example `Created the user interface for creating viewing multiple articles` should be `Created the user interface for viewing multiple articles`

2019-02-19 13:09 UTC, KMaina commented
Good job so far. I had a suggestion regarding displaying all the articles. Perhaps you could have rendered more than 1 article for where you are getting all articles. This way we can have a better feel of how the UI would look like in such a scenario.

2019-02-19 13:10 UTC, MaggieChege commented
Good work. For the Like and dislike, you can add thumbs up and thumbs down icons

2019-02-19 13:33 UTC, cosmas28 requested changes

2019-02-19 13:33 UTC, cosmas28 commented on src/pages/ArticleDetail/ArticDetail.test.jsx
> +describe('Get Articles', () => {
This title is confusing, what do you think about `The ArticleDetail`?

2019-02-19 13:33 UTC, cosmas28 commented on src/pages/HomePage/HomePage.test.jsx
> +describe('Get Articles', () => {
The same thing in this title, kindly make it descriptive.

2019-02-19 14:12 UTC, SelaDanti commented on src/pages/HomePage/HomePage.test.jsx
> +describe('Get Articles', () => {
I have used HomePage since its the name of the component I am  testing

2019-02-19 14:30 UTC, cosmas28 requested changes

2019-02-19 14:30 UTC, cosmas28 commented on src/pages/HomePage/index.jsx
> +        <div className="card bg-secondary text-white">
there is a lot of repetition here, kindly create a separate component for presenting one article and then reuse it in this component, ie, `SingleArticle` component.

2019-02-19 14:48 UTC, SelaDanti commented on src/pages/HomePage/index.jsx
> +        <div className="card bg-secondary text-white">
I have created a component called ArticlePanel that will be reusable

2019-02-19 20:04 UTC, cosmas28 commented
Kindly rebase from develop

2019-02-19 20:07 UTC, cosmas28 requested changes

2019-02-19 20:07 UTC, cosmas28 commented on src/components/ArticlePanel/ArticlePanel.test.jsx
> +describe('HomePage', () => {
Any reason why this title is `HomePage` and yet you are testing `<ArticlePanel />`?

2019-02-20 06:55 UTC, kwameasiago commented on src/components/ArticlePanel/ArticlePanel.test.jsx
> +describe('HomePage', () => {
I forgot to update the test. I have done that now

2019-02-20 14:08 UTC, cosmas28 approved these changes

2019-02-20 14:08 UTC, merged