#163783282  Update Readme
andela/ah-django-unchained-frontend pull request #2
Opened 2019-02-07 09:11 UTC by MaggieChege

**What does this PR do?**

 - Update the Readme

**Description of Task to be completed?**

-  Update the Readme File

2019-02-07 10:36 UTC, andrewhingah approved these changes

2019-02-07 12:19 UTC, cosmas28 requested changes

2019-02-07 12:19 UTC, cosmas28 commented on README.md
> +``` npm start ```
- Goodjob @MaggieChege. On top of that, I would urge you to add another section where you are going list all the stacks used in this project.

- please add section for testing too.

2019-02-07 12:24 UTC, MaggieChege commented on README.md
> +``` npm start ```
Okay adding that.

2019-02-07 12:40 UTC, kwameasiago approved these changes

2019-02-07 12:46 UTC, Georgeygigz approved these changes
Looks good to me

2019-02-08 09:34 UTC, cosmas28 requested changes
Under the `Stacks used in the Project` section I don't see testing stack, styling stack. Kindly add them.

2019-02-11 07:13 UTC, cosmas28 approved these changes

2019-02-11 07:14 UTC, merged