#162948806 create draft article
andela/ah-django-unchained-frontend pull request #20
Opened 2019-02-19 16:03 UTC by d-kahara

#### What does this PR do?
Creates a user Interface through which a user can be able to create an article.

#### Description of Task to be completed?
* [x]   Create a folder structure
* [x]   Configure Redux and thunk middleware
* [x]   Consume the `post article` API endpoint
* [x]   Write Tests

#### How should this be manually tested?
1. Clone this repository on your local machine using
   `git clone https://github.com/andela/ah-django-unchained-frontend.git`
2. Change your working directory to the project's directory using
   `cd ah-django-unchained-frontend`
3. Change to the specific branch `ft-create-draft-article-162948806 ` using
   `git checkout ft-create-draft-article-162948806 `
4. Create a `.env` file and inside it add this line `REACT_APP_BASE_URL=app-base-url` where `app-base-url ` is the root url of the backend API
5. Run `npm install` to install all the modules listed in the `package.json` file.
6. Run `npm start` command to start the application.
7. The application should start successfully. On the browser, navigate to the URL `http://localhost:3000/post-article`, .

#### Link to PT story
[#162948806 ](https://www.pivotaltracker.com/story/show/162948806)

2019-02-23 14:41 UTC, cosmas28 requested changes

2019-02-23 14:41 UTC, cosmas28 commented on src/store/modules/articles/postArticles/index.js
> +export const postArticleRequestAction = () => ({
The `Action` postfix is not necessary in this function name, it should be `postArticleRequest`.

2019-02-23 15:21 UTC, cosmas28 commented
Kindly fix merge conflicts.

2019-02-28 06:17 UTC, cosmas28 requested changes

2019-02-28 06:17 UTC, cosmas28 commented on src/pages/CreateArticle/index.jsx
> +        <form onSubmit={this.handleSubmit}>
Kindly reuse the `ArticleForm` component to avoid repetition of article forms. Sync with @KMaina to show you how to reuse the form.

2019-02-28 06:21 UTC, d-kahara commented on src/pages/CreateArticle/index.jsx
> +        <form onSubmit={this.handleSubmit}>
noted

2019-02-28 12:27 UTC, Georgeygigz commented on src/pages/CreateArticle/CreateArticle.test.js
> +    it('Should dispatch postArticle', () => {
@d-kahara Good work here, but the description of `it block should start with a lower case`.

2019-02-28 12:27 UTC, Georgeygigz commented on src/pages/CreateArticle/CreateArticle.test.js
> +    it('Should dispatch uploadImage', () => {
ditto

2019-02-28 12:40 UTC, SelaDanti commented
Since the description can contain a paragraph consider using a textarea instead of an input box

2019-02-28 12:56 UTC, d-kahara commented
> Since the description can contain a paragraph consider using a textarea instead of an input box. Other than that everything looks fine.

The PR for UI components was raised and merged earlier.

2019-02-28 14:40 UTC, andrewhingah commented
Good work @d-kahara.
Kindly change the `
Creates a user Interface through which a user can be able to create an article.` to `
Creates a user Interface through which a user can be able to create and save an article as draft.`

2019-03-01 03:24 UTC, cosmas28 commented
Kindly add a proper navigation button/link to create the article page.

2019-03-01 06:45 UTC, d-kahara commented
> * Kindly add a proper navigation button/link to create the article page.
> * Should also use the toaster to display a success/error message.

@SelaDanti is handling navigation links in the navbar, will tell him to add a link as you have requested

2019-03-01 07:54 UTC, cosmas28 approved these changes

2019-03-01 07:54 UTC, merged