#162948806 Create the Form for Editing and Creating Articles
andela/ah-django-unchained-frontend pull request #22
Opened 2019-02-21 08:41 UTC by KMaina

#### What does this PR do?
Create a page that allows users to edit an article
#### Description of Task to be completed?
Have a page that contains input fields, an editor and button for updating an artcle.
#### How should this be manually tested?
- Clone the repo locally.
- Checkout to the `ft-update-article-UI-162948806 branch`.
- Run `npm install` to install all dependencies.
- Navigate to the `/updatearticle` page to view the form.
#### Any background context you want to provide?
- In order to have a uniform look and feel for the app, we made sure that the forms used in creating, drafting and editing an article.
- for the case of editing an article, data will be populated into the form inputs allowing for a user to edit as they please. Upon updating this will then be changed in the database.
#### What are the relevant pivotal tracker stories?
[#162948806](https://www.pivotaltracker.com/story/show/162948806)

2019-02-21 08:48 UTC, MaggieChege commented
Add screenshots to show the UI.

2019-02-21 09:01 UTC, Georgeygigz approved these changes
looks good to me

2019-02-21 12:51 UTC, cosmas28 requested changes

2019-02-21 12:51 UTC, cosmas28 commented on src/components/TextArea/index.jsx
> +import React from 'react';
Good job here though I don't see anywhere you are using this component, any reason why you created this?

2019-02-21 12:56 UTC, KMaina commented on src/components/TextArea/index.jsx
> +import React from 'react';
We had created this initially but decided to use a text editor(ck-editor) instead to allow for people to properly format their documents as they wish. We then realized the editor came with its own text area. We decided not to get rid of it in case someone wanted to use the text area when creating the comments component.

2019-02-22 12:51 UTC, cosmas28 approved these changes

2019-02-22 12:59 UTC, cosmas28 requested changes

2019-02-22 12:59 UTC, cosmas28 commented on src/pages/UpdateArticle/index.jsx
> +export class UpdateArticle extends Component {
What do you think about naming this component as `ArticleForm`? This is because it is going to be used for both creating and updating an article. Additionally, since it's going to be a presentational component, you should also move it to the `components` directory.

2019-02-23 12:42 UTC, KMaina commented on src/pages/UpdateArticle/index.jsx
> +export class UpdateArticle extends Component {
I think I can rename the form then and move it too

2019-02-24 18:22 UTC, cosmas28 requested changes

2019-02-24 18:22 UTC, cosmas28 commented on src/components/ArticleForm/index.jsx
> +export class ArticleForm extends Component {
@KMaina Sorry for the inconvenience, I think this component should be in the `pages` directory...I came to think about it that it should be connected to the redux state  so that it can be used for editing the articles too.

2019-02-24 18:22 UTC, cosmas28 commented on src/routes/Routes.jsx
> +          <Route updatearticle path="/updatearticle" component={ArticleForm} />
Kindly add the `Add article button` in the article detail page to allow users to easily navigate to this route.

2019-02-24 18:49 UTC, KMaina commented on src/routes/Routes.jsx
> +          <Route updatearticle path="/updatearticle" component={ArticleForm} />
- For the first feedback - I am handling updating of articles not the creation of articles. Maybe that can be handled by the people who are handling that.
- In line with the feedback given on adding the button, maybe I can add an `update article button` on the page where we are editing a single article once it is merged?

2019-02-25 11:02 UTC, KMaina commented on src/components/ArticleForm/index.jsx
> +export class ArticleForm extends Component {
moved to pages

2019-02-25 13:37 UTC, cosmas28 approved these changes

2019-02-25 13:38 UTC, merged