#162948806 get one article
andela/ah-django-unchained-frontend pull request #24
Opened 2019-02-21 16:11 UTC by SelaDanti

#### What does this PR do?
Enable users to fetch single article via a slug

#### Description of Task to be completed?
* [x]   Create actions for fetching a single article
* [x]   Create reducer for fetching a single article
* [x]   Consume the `get  single article` API endpoint
* [x]   Created test for the front end

#### How should this be manually tested?
1. Clone this repository on your local machine using
   `git clone https://github.com/andela/ah-django-unchained-frontend.git`
2. Change your working directory to the project's directory using
   `cd ah-django-unchained-frontend`
3. Change to the specific branch `ft-get-one-article-1629488 ` using
   `git checkout ft-get-one-article-16294880 `
4. Create a `.env` file and inside it add this line `REACT_APP_BASE_URL=app-base-url` where `app-base-url ` is the root url of the backend API
5. Run `npm install` to install all the modules listed in the `package.json` file.
6. Run `npm start` command to start the application.
7. The application should start successfully. On the browser, navigate to the URL `http://localhost:3000/article/name-of-article`, .

#### Link to PT story
[#162948806](https://www.pivotaltracker.com/story/show/162948806)

2019-02-21 17:04 UTC, Georgeygigz commented on src/store/modules/articleDetail/index.js
> +export default singleArticleReducer;
kindly add a blank line at the end of the file

2019-02-21 17:05 UTC, Georgeygigz commented on src/store/modules/articleDetail/type.js
> +export const ARTICLE_FAIL = 'ARTICLE_FAIL';
ditto

2019-02-22 02:45 UTC, MaggieChege commented on src/store/modules/articleDetail/articleDetail.reduce.test.jsx
> +    };
Rename file to articledDetail.reducers.test.jsx

2019-02-22 17:41 UTC, andrewhingah commented on src/store/modules/articleDetail/articleDetail.actions.test.jsx
> +describe('ArticleSingle', () => {
The title of your describe block should be the name of the component you are testing, in this case `ArticleDetail`

2019-02-22 17:42 UTC, andrewhingah commented on src/store/modules/articleDetail/articleDetail.reducers.test.jsx
> +    expect(singleArticleReducer({},action)).toEqual(expectedData);
Please remove this blank line

2019-02-22 17:43 UTC, andrewhingah commented on src/store/modules/articleDetail/articleDetail.reducers.test.jsx
> +    expect(singleArticleReducer({},action)).toEqual(expectedData);
ditto

2019-02-22 17:43 UTC, andrewhingah commented on src/store/modules/articleDetail/articleDetail.reducers.test.jsx
> +    expect(singleArticleReducer({},action)).toEqual(expectedData);
ditto

2019-02-23 13:34 UTC, SelaDanti commented on src/store/modules/articleDetail/articleDetail.reducers.test.jsx
> +    expect(singleArticleReducer({},action)).toEqual(expectedData);
I put that line there for readability

2019-02-23 14:51 UTC, cosmas28 commented
Kindly Fix merge conflicts.

2019-02-25 11:27 UTC, cosmas28 requested changes

2019-02-25 11:27 UTC, cosmas28 commented on src/store/modules/articleDetail/type.js
> +export const ARTICLE_SUCCESS = 'ARTICLE_SUCCESS';
This action types should more descriptive, ie. for instance, `GET_SINGLE_ARTICLE_SUCCESS`

2019-02-26 07:14 UTC, KMaina commented on src/components/NotFound/NotFound.test.jsx
> +describe('NotFound', ()=>{
Maybe you can have spaces after the parenthesis and opening brace

2019-02-26 07:20 UTC, KMaina commented on src/store/modules/articleDetail/articleDetail.actions.test.jsx
> +      status: 201,
fetching an article should have a status code of 200

2019-02-26 07:21 UTC, KMaina commented on src/store/modules/articleDetail/articleDetail.actions.test.jsx
> +      data: { status: 201 }
look at the comment above

2019-02-26 07:23 UTC, KMaina commented on src/store/modules/articleDetail/articleDetail.reducers.test.jsx
> +    isFetch: false
indent this line here

2019-02-26 07:24 UTC, KMaina commented on src/store/modules/articleDetail/articleDetail.reducers.test.jsx
> +    isFetch: true,
indent code within this block

2019-02-26 07:24 UTC, KMaina commented on src/store/modules/articleDetail/articleDetail.reducers.test.jsx
> +    isFetch: false,
indent this line

2019-02-26 08:15 UTC, KMaina commented on src/pages/ArticleDetail/ArticDetail.test.jsx
> +      IsFetch:false,
kindly add a space after `IsFetch` to make your code meet linting standards

2019-02-26 08:16 UTC, KMaina commented on src/pages/ArticleDetail/ArticDetail.test.jsx
> +      IsFetch:false
kindly add a space after `IsFetch` to make your code meet linting standards

2019-02-26 09:07 UTC, d-kahara commented on src/store/modules/articleDetail/articleDetail.reducers.test.jsx
> +      type: undefined
Any reason why this action type is declared as `undefined` ?

2019-02-26 14:36 UTC, SelaDanti commented on src/store/modules/articleDetail/articleDetail.reducers.test.jsx
> +      type: undefined
am testing initial state that uses the default state

2019-02-26 14:37 UTC, cosmas28 requested changes

2019-02-26 14:37 UTC, cosmas28 commented on src/store/modules/articleDetail/index.js
> +const  failSingleArticleFail = payload  => ({
The name of this action creator is not descriptive enough, kindly sync with your teammates to refactor all the action names.

2019-02-26 14:37 UTC, cosmas28 commented on src/store/modules/articleDetail/index.js
> +export const singleArticleReducer = (state = {data: {}}, action) =>{
The `Reducer` prefix in this reducer is not necessary, kindly remove it.

2019-02-26 14:39 UTC, cosmas28 commented
Kindly note the following:
- rebase from developing and fix the conflicts.
- add proper navigation for a single article from the Article list page.

2019-02-26 20:49 UTC, andrewhingah commented on src/store/modules/articleDetail/articleDetail.reducers.test.jsx
> +  it('should run with ARTICLE FAIL return isFetch true', () => {
The title of this `it` block is confusing. The isFetch returns false, and not true as stated.

2019-02-27 02:22 UTC, andrewhingah commented on src/store/modules/articleDetail/articleDetail.reducers.test.jsx
> +      type: undefined
It doesn't return undefined when I ran locally. 
``` Expected value to equal:
      {"data": undefined, "isFetch": true}
    Received:
      {"isFetch": false, "isFound": true}```

2019-02-27 06:40 UTC, SelaDanti commented on src/store/modules/articleDetail/articleDetail.reducers.test.jsx
> +      type: undefined
I have made changes please pull and try again

2019-02-27 07:23 UTC, cosmas28 requested changes

2019-02-27 07:23 UTC, cosmas28 commented on src/store/modules/articleDetail/index.js
> +export const singleArticleReducer = (state = {data: {}}, action) =>{
Any reason why this feedback has not been implemented?

2019-02-27 08:24 UTC, SelaDanti commented on src/store/modules/articleDetail/index.js
> +export const singleArticleReducer = (state = {data: {}}, action) =>{
I have fixed it

2019-02-27 08:27 UTC, MaggieChege commented on src/store/modules/articleDetail/type.js
> +export const GET_SINGLE_ARTICLE_REQUEST = 'GET_SINGLE_ARTICLE_REQUEST';
Add Blank line at the end of this file

2019-02-27 09:08 UTC, KMaina commented on src/pages/ArticleDetail/index.jsx
> +
Kindly remove this space if it is not necessary

2019-02-28 02:01 UTC, d-kahara commented
On Instruction no.7 of the PR, shouldn't one navigate to 
 `http://localhost:3000/article/article-slug`?

The Pivotal Tracker Story ID used in the PR header and provided as a link belongs to `Users should be able to create articles`

2019-02-28 05:05 UTC, cosmas28 approved these changes

2019-02-28 05:07 UTC, merged