feat(article) get article draft
andela/ah-django-unchained-frontend pull request #25
Opened 2019-02-22 08:45 UTC by MaggieChege

#### What does this PR do?
Creates a user interface where a user can view  own drafts
#### Description of Task to be completed?
* [x]    Reuse UI components
* [x]    Configure Redux and thunk middleware
* [x]    Consume the `get article draft` API endpoint
* [x]    Write Tests for both Reducers and Actions.

#### How should this be manually tested?
1. Clone this repository on your local machine using
   `git clone https://github.com/andela/ah-django-unchained-frontend.git`
2. Change your working directory to the project's directory using
   `cd ah-django-unchained-frontend`
3. Change to the specific branch `ft-create-draft-article-162948806 ` using
   `git checkout ft-view-draft-162948806 `
4. Create a `.env` file and inside it add this line `REACT_APP_BASE_URL=app-base-url` where `app-base-url ` is the root url of the backend API
5. Run `npm install` to install all the modules listed in the `package.json` file.
6. Run `npm start` command to start the application.
7. The application should start successfully. On the browser, navigate to the URL 
login navigate to  `http://localhost:3000/login`
You will be redirected to view drafts `http://localhost:3000/draft`

#### Link to PT story[#162948806](https://www.pivotaltracker.com/story/show/162948806)

2019-02-22 14:20 UTC, SelaDanti commented on src/pages/ViewDraft/ViewDraft.scss
> +}
Add a line at the end of the file

2019-02-22 14:21 UTC, SelaDanti commented on src/pages/ViewDraft/ViewDrafts.test.jsx
> +});
ditto

2019-02-25 06:33 UTC, Georgeygigz commented on src/pages/ViewDraft/index.jsx
> +            <div className="container" key={article.id}>
From what @cosmas28 adviced, it not a good practice to have presentation component inside your container component. You can kindly consider refactoring this.

2019-02-25 07:28 UTC, MaggieChege commented on src/pages/ViewDraft/index.jsx
> +            <div className="container" key={article.id}>
I will refactor this.

2019-02-26 13:10 UTC, andrewhingah commented on src/pages/ViewDraft/ViewDrafts.test.jsx
> +
Remove this extra line

2019-02-26 13:11 UTC, andrewhingah commented on src/pages/ViewDraft/ViewDrafts.test.jsx
> +it('should render get draft articles', () => {
Consider adding an empty line here.

2019-02-26 13:13 UTC, andrewhingah commented on src/pages/ViewDraft/index.jsx
> +
These empty lines are unnecessary. Kindly remove them.

2019-02-27 07:41 UTC, cosmas28 requested changes

2019-02-27 07:41 UTC, cosmas28 commented on src/store/modules/drafts/index.js
> +export const getRequest = () => ({
Your action creators are not descriptive enough, kindly refactor them.

2019-02-27 07:45 UTC, cosmas28 requested changes

2019-02-27 07:45 UTC, cosmas28 commented on src/pages/LoginPage/index.jsx
> +      return <Redirect to="/draft" />;
I think authenticated users should be redirected to the published articles, this will enhance a proper UX for the new users. What do you think?

2019-02-27 07:53 UTC, MaggieChege commented on src/pages/LoginPage/index.jsx
> +      return <Redirect to="/draft" />;
Yes I agree with you. I will remove this and a user will be redirected to view  drafts once he/she creates an article draft.

2019-02-27 09:21 UTC, KMaina commented on src/pages/ViewDraft/ViewDrafts.test.jsx
> + wrapper = shallow(<ViewDrafts {...props} />);
kindly indent this line here

2019-02-27 09:21 UTC, KMaina commented on src/pages/ViewDraft/ViewDrafts.test.jsx
> +import React from 'react';
Perhaps you could rename the file from `ViewDrafts.test.jsx` to `ViewDraft.test.jsx`

2019-02-27 09:33 UTC, andrewhingah commented on src/store/rootReducer.js
> +import {getDraftReducer}  from './modules/drafts/index';
Include spaces before and after `getDraftReducer`

2019-02-27 09:46 UTC, SelaDanti commented on src/pages/ViewDraft/ViewDraft.test.jsx
> +  expect(props.isFetching).toEqual(state.getDraftReducer.isFetching);
I think this should be in an it block

2019-02-27 09:48 UTC, SelaDanti commented on src/pages/ViewDraft/index.jsx
> +    const articles = this.props.response;
Consider using destructuring

2019-02-27 10:36 UTC, MaggieChege commented on src/pages/ViewDraft/ViewDraft.test.jsx
> +  expect(props.isFetching).toEqual(state.getDraftReducer.isFetching);
I prefer leaving it like this because am testing them individually

2019-02-27 12:23 UTC, d-kahara commented on src/store/modules/drafts/viewdraft.reducers.test.js
> +
unnecessary blank line

2019-02-28 09:58 UTC, cosmas28 approved these changes

2019-02-28 09:59 UTC, merged