#162948806 Get all articles redux
andela/ah-django-unchained-frontend pull request #26
Opened 2019-02-22 11:37 UTC by Georgeygigz

**What does this PR do?**

* It creates functionality for listing all articles

**Description of Task to be completed?**

* Adding functionality for listing all articles

**How should this be manually tested?**

* clone this repo `https://github.com/andela/ah-django-unchained-frontend`
* `cd ah-django-unchained-frontend`
* `git checkout ft-list-articles-162948806`
* Install the required dependencies `npm install`
* `npm start to run the local server`

**Pivotal Tracker story**
[#162948804](https://www.pivotaltracker.com/story/show/162948804)

**Screenshot**
![image](https://user-images.githubusercontent.com/24627269/53240229-2fc30f00-36af-11e9-82b5-f3bec365092a.png)

2019-02-22 13:18 UTC, SelaDanti commented on src/pages/AllArticles/allarticles.test.js
> +  beforeEach(() => {
Add a line for readability

2019-02-22 13:26 UTC, SelaDanti commented on src/store/modules/getArticles/types.js
> +export const GET_ALL_ARTICLES_FAILURE = 'GET_ALL_ARTICLES_FAILURE';
Add a line at the end of the file

2019-02-23 09:19 UTC, andrewhingah commented
Good work George. However, you can change the body of your commit message from `Write test for getting functionality` to `Write test for getting all articles`. This will be more descriptive.

2019-02-23 09:25 UTC, andrewhingah commented on src/pages/AllArticles/allarticles.test.js
> +describe('Get All articles', () => {
I think the title of the describe block should be the name of the component. For instance, `AllArticles` and not `Get All Articles`. But @cosmas28 can confirm this.

2019-02-23 15:08 UTC, cosmas28 commented on src/pages/AllArticles/allarticles.test.js
> +describe('Get All articles', () => {
I agree with @andrewhingah

2019-02-23 16:50 UTC, Georgeygigz commented on src/pages/AllArticles/allarticles.test.js
> +describe('Get All articles', () => {
I have already implemented this.

2019-02-24 18:48 UTC, cosmas28 requested changes

2019-02-24 18:48 UTC, cosmas28 commented on src/components/ArticlePanel/index.jsx
> +        <AllArticles />
- It's not a good practice to nest container component to a presentational component.
- Kindly undo these changes and pass props to replace the dummy data in the `ArticlePanel` component.

2019-02-24 18:48 UTC, cosmas28 commented on src/pages/AllArticles/index.jsx
> +export class AllArticles extends Component {
I don't think the `AllArticles` component is needed. Use the home `HomaPage` component to display all the articles. Kindly take time to learn the code base carefully reuse the available properly. Sync with @SelaDanti to explain the use of the `HomePage` and `ArticlePanel` components.

2019-02-24 19:44 UTC, Georgeygigz commented on src/components/ArticlePanel/index.jsx
> +        <AllArticles />
Okay will work on this

2019-02-24 19:44 UTC, Georgeygigz commented on src/pages/AllArticles/index.jsx
> +export class AllArticles extends Component {
Okay thanks, working on this.

2019-02-25 13:42 UTC, cosmas28 commented on src/store/modules/getArticles/getarticles.actions.test.js
> +import { GET_ALL_ARTICLES_SUCCESS, GET_ALL_ARTICLES_REQUEST } from './types';
I like the way you named this action. Keep it up.

2019-02-25 13:44 UTC, cosmas28 commented on src/store/modules/getArticles/index.js
> +import * as types from './types';
In the file, I also like the way you named your actions. Keep it up.

2019-02-25 13:53 UTC, Georgeygigz commented on src/store/modules/getArticles/getarticles.actions.test.js
> +import { GET_ALL_ARTICLES_SUCCESS, GET_ALL_ARTICLES_REQUEST } from './types';
Thanks, I will try and stick to this

2019-02-25 13:53 UTC, Georgeygigz commented on src/store/modules/getArticles/index.js
> +import * as types from './types';
Thanks, I will try and stick to this

2019-02-25 14:08 UTC, cosmas28 requested changes

2019-02-25 14:08 UTC, cosmas28 commented on src/pages/HomePage/index.jsx
> +    const articlesList = articles.articles.length ? (
Two feedback about this logic here:
- It is not a good practice to have this condition here, so please do this in the `return` statement.
- the `No articles` message is displayed even when the page is loading, I think it should only show up when the loader has stopped.

2019-02-25 14:13 UTC, Georgeygigz commented on src/pages/HomePage/index.jsx
> +    const articlesList = articles.articles.length ? (
Okay I will work on this

2019-02-26 07:06 UTC, cosmas28 approved these changes

2019-02-26 07:06 UTC, merged