#162948806 Delete a Posted Article
andela/ah-django-unchained-frontend pull request #29
Opened 2019-02-26 09:14 UTC by KMaina

#### What does this PR do?
Allows for an authenticated user to delete an article
#### Description of Task to be completed?
Delete an article that has been posted by a user.
#### How should this be manually tested?
- Clone the repo locally.
- Checkout to the `ft-delete-article-162948806 branch`.
- Run `npm install` to install all dependencies.
- Navigate to the `/login` page to login successfully.
- Navigate to the `/article/:article` page and click on the delete button.
#### Any background context you want to provide?
- I might have some errors in the `ArticleDetail` page since I rebased off a branch that was yet to be merged. Hopefully, their work will be successfully merged and I can rebase to get the right changes.
- You can only delete an article you created.
#### What are the relevant pivotal tracker stories?
[#16294880](https://www.pivotaltracker.com/story/show/162948806)

2019-02-28 02:16 UTC, d-kahara commented on src/pages/ArticleDetail/index.jsx
> +  deleteArticle: (article, st) => dispatch(deleteArticle(article, st))
Consider renaming `st` to something a bit more descriptive

2019-02-28 11:33 UTC, Georgeygigz commented
Good work @KMaina, Kindly rebase your work

2019-02-28 11:36 UTC, Georgeygigz commented
Good work @KMaina, kindly rebase your work

2019-02-28 16:55 UTC, andrewhingah commented
Looks good

2019-02-28 16:56 UTC, SelaDanti commented on src/pages/ArticleDetail/index.jsx
> +                      alt=''
Don't leave alt attribute empty

2019-02-28 17:29 UTC, MaggieChege approved these changes
Looks Good to me

2019-02-28 18:05 UTC, SelaDanti commented
Look good to me

2019-03-01 06:18 UTC, cosmas28 requested changes
The test coverage in the `ArticleDetail` component has reduced because of the changes you added, please test the lines you added.

2019-03-01 13:47 UTC, KMaina commented on src/store/modules/deleteArticle/index.js
> +  ARTICLE_DELETE_REQUEST,
change to `DELETE_ARTICLE_REQUEST`

2019-03-01 13:49 UTC, KMaina commented on src/store/modules/deleteArticle/index.js
> +export const deletePostedArticle = (articleSlug, deletedStatus) => dispatch => {
change to `deleteArticle`

2019-03-01 13:49 UTC, KMaina commented on src/store/modules/deleteArticle/index.js
> +export const deleteArticle = (state = initialState, action) => {
change to `deleteArticleReducer`

2019-03-01 14:59 UTC, cosmas28 approved these changes

2019-03-01 14:59 UTC, merged