#162948799 Set Up SASS processing on the client
andela/ah-django-unchained-frontend pull request #3
Opened 2019-02-07 09:15 UTC by andrewhingah

**What does this PR do?**
Installs and sets up `sass` pre-processing on the application to enables the use of both `.scss` and `.css` files on the client

**Description of tasks to be completed**
- install node-sass
- rename `src/App.css` to `src/App.scss`
- rename `src/index.css` to `src/index.scss`

**Relevant Pivotal Tracker Story**
[#162948799](https://www.pivotaltracker.com/story/show/162948799)

2019-02-07 11:32 UTC, kwameasiago approved these changes
Looks good to me

2019-02-07 12:06 UTC, cosmas28 requested changes

2019-02-07 12:06 UTC, cosmas28 commented on package.json
> +    "node-sass": "^4.11.0",
- @andrewhingah Good job here. However, you should one more package for compiling Sass into CSS.

- next, edit the `webpack.config.dev.js` in the config folder as follows. Add the installed Sass loaders to configure the`webpack` to be able to compile our `scss` files.

- Also, move dependencies for compiling Sass into the devDependencies because they are required mostly in development.

2019-02-07 12:14 UTC, andrewhingah commented on package.json
> +    "node-sass": "^4.11.0",
Noted. Let me work on that.

2019-02-08 14:57 UTC, cosmas28 approved these changes

2019-02-08 14:57 UTC, merged