#162948798 Create routers
andela/ah-django-unchained-frontend pull request #4
Opened 2019-02-07 11:29 UTC by SelaDanti

### What does this PR do?
Create two routes for  login and home page

### Description of tasks accomplished

- Installed and configured Routers
- Added two routes login and Home
- Created directories component and view respectively 
- Added dummy a component and view

### How this app should be tested?
clone this repo and checkout to ch-setup-react-router-162948798. install package requirement and run npm start to run the app

### Related pivotal tracker stories
[#162948798](https://www.pivotaltracker.com/story/show/162948798)

### Screenshots
<img width="1280" alt="screenshot 2019-02-07 at 14 27 48" src="https://user-images.githubusercontent.com/30651751/52408782-af17e680-2ae4-11e9-8823-c3c68a784656.png">

<img width="1280" alt="screenshot 2019-02-07 at 14 27 56" src="https://user-images.githubusercontent.com/30651751/52408794-b3dc9a80-2ae4-11e9-9aad-64a0100a9369.png">

2019-02-07 12:17 UTC, Georgeygigz commented on src/components/Login.jsx
> +export default Login;
Add a blank line at the end this file

2019-02-07 12:18 UTC, Georgeygigz commented on src/view/Home.jsx
> +export default Home;
ditto

2019-02-07 12:24 UTC, MaggieChege approved these changes
Looks good to me

2019-02-07 12:47 UTC, Georgeygigz approved these changes
Looks good to me

2019-02-07 13:03 UTC, KMaina commented on src/App.jsx
> +      {/* <div> */}
Kindly remove this line of code that is commented

2019-02-07 13:04 UTC, KMaina commented on src/App.jsx
> +      {/* </div> */}
ditto

2019-02-07 13:06 UTC, KMaina approved these changes

2019-02-08 08:40 UTC, cosmas28 requested changes

2019-02-08 08:40 UTC, cosmas28 commented on src/App.jsx
> +      <BrowserRouter>
It's a good practice to create a route component on it's on file. ie `src/routes/routes.js`. Therefore, move these dummy routes to their own directory and nest the `Route component` as a child component of the `App component`.

2019-02-08 08:59 UTC, SelaDanti commented on src/App.jsx
> +      <BrowserRouter>
Ok will do that

2019-02-08 09:17 UTC, cosmas28 commented on src/components/routes.jsx
> +class Routes extends Component {
Any reason why this is a class-based component?

2019-02-08 09:22 UTC, cosmas28 requested changes
I requested the `Route component` to be under `src/routes/routes.jsx` tree. Why did you move it to `src/components`?

2019-02-08 09:24 UTC, SelaDanti commented on src/components/routes.jsx
> +class Routes extends Component {
No reason. Just preference, Should I change to functional components?

2019-02-11 07:25 UTC, cosmas28 requested changes

2019-02-11 07:25 UTC, cosmas28 commented on src/view/Home.jsx
> +        return (
Kindly fix the indentation from line 4 to line 8.

2019-02-11 07:25 UTC, cosmas28 commented on src/view/Home.jsx
> +export default Home;
There should be a line space before this line. This makes your code more readable.

2019-02-11 09:08 UTC, cosmas28 requested changes

2019-02-11 09:08 UTC, cosmas28 commented on src/view/Home.jsx
> +export default Home;
The indentation space should be consistent in all components. Kindly use two spaces like the way it is on `Login` and `Routes` components.

2019-02-11 14:19 UTC, cosmas28 approved these changes

2019-02-11 14:19 UTC, merged