#162948796 Setup Environment for tests.
andela/ah-django-unchained-frontend pull request #5
Opened 2019-02-07 12:55 UTC by MaggieChege

### What does this PR do?
Setup environment for writing tests

### Description of tasks accomplished

Setup Environment for test

### How this app should be tested?
- clone this repo https://github.com/andela/ah-django-unchained-frontend.git and checkout to ch-setup-tests-environment-162948796. 
- Run ``` npm test ```

### Related pivotal tracker stories
[#162948796](https://www.pivotaltracker.com/story/show/162948796)

2019-02-07 13:14 UTC, KMaina approved these changes

2019-02-07 16:43 UTC, cosmas28 commented
- Kindly adhere to the [engineering-playbook](https://github.com/andela/engineering-playbook/blob/master/5.%20Developing/Conventions/readme.md#commit-message) when writing your commit messages.

- Stash your commit messages and remain with only one commit message.

2019-02-07 17:06 UTC, cosmas28 requested changes
Kindly configure the following:
- jest.config.js file(add the necessary configurations)
- tell Jest the path from where it can get configurations for enzyme
- add scripts for `test:watch` and `test:coverage` in the `package.json` file.

2019-02-08 10:18 UTC, cosmas28 requested changes

2019-02-08 10:18 UTC, cosmas28 commented on package.json
> +    "enzyme": "^3.8.0",
The dependencies `react-scripts`, `watch`, `enzyme` and `enzyme-adapter-react-16` should be under the `devDependencies`. This is because they are only needed during the development stage.

2019-02-08 10:25 UTC, cosmas28 requested changes

2019-02-08 10:25 UTC, cosmas28 commented on jest.config.js
> +
Kindly tell jest to ignore the test coverage for the `serviceWorker.jsx` file.

2019-02-08 14:36 UTC, cosmas28 approved these changes

2019-02-08 14:40 UTC, merged