#163860903 Navigation Bar
andela/ah-django-unchained-frontend pull request #9
Opened 2019-02-11 22:45 UTC by Georgeygigz

**What does this PR do?**
* It adds a  Navigation bar

**Description of Task to be completed?**

* Adding a Navigation bar.`

**How should this be manually tested?**

* clone this repo `https://github.com/andela/ah-django-unchained-frontend`
* `cd ah-django-unchained-frontend`
* `git checkout ft-navbar-163860903`
* Install the required dependencies `npm install`
* `npm start to run the local server`

**Pivotal Tracker story**
[#163860903](https://www.pivotaltracker.com/story/show/163860903)

![image](https://user-images.githubusercontent.com/24627269/52598515-fd234600-2e66-11e9-9c3e-1e61a6f9a824.png)

2019-02-12 07:07 UTC, cosmas28 commented
@Georgeygigz kindly fix the failing tests on travis

2019-02-12 07:17 UTC, cosmas28 requested changes

2019-02-12 07:17 UTC, cosmas28 commented on src/App.jsx
> +    <NavBar />
Kindly indent the `<NavBar/>` and `<Routes/>` here. This will make the code clean, consistent and readable.

2019-02-12 07:17 UTC, cosmas28 commented on src/pages/NavBar.jsx
> +import React, { Component } from 'react';
Move the This component to the `src/components/NavBar/index.jsx` since it is going to be used mostly as a presentational component rather than a container component.

2019-02-12 07:36 UTC, cosmas28 requested changes

2019-02-12 07:36 UTC, cosmas28 commented on src/routes/routes.jsx
> -
Any reason why you removed this line here?

2019-02-12 07:36 UTC, cosmas28 commented on src/routes/routes.jsx
> +export default Routes
There should a line space at the end of each file.

2019-02-12 07:36 UTC, cosmas28 commented on src/pages/NavBar.jsx
> +  render() {
There should be a line space before any method definition.

2019-02-12 07:36 UTC, cosmas28 commented on src/pages/NavBar.jsx
> +    this.navBarToggle = this.navBarToggle.bind(this);
Any reason why you bind this toggle method?

2019-02-12 07:36 UTC, cosmas28 commented on src/pages/NavBar.jsx
> +  navBarToggle() {
Kindly adhere to the method naming conventions. All methods should be in form of a verb, for instance, this method should be like `toggleNavBar`.

2019-02-12 07:41 UTC, cosmas28 commented on src/pages/NavBar.jsx
> +  navBarToggle() {
Also use the `Arrow` function technique here to avoid binding the `this` keyword.

2019-02-12 08:53 UTC, Georgeygigz commented on src/App.jsx
> +    <NavBar />
Okay working on it

2019-02-12 08:53 UTC, Georgeygigz commented on src/pages/NavBar.jsx
> +import React, { Component } from 'react';
Okay working on it

2019-02-12 09:09 UTC, Georgeygigz commented on src/routes/routes.jsx
> -
Okay will fix this

2019-02-13 15:18 UTC, cosmas28 commented
The head of your commit messages is the same, in such its advisable to have one commit message. So, please stash your commit messages.

2019-02-13 15:38 UTC, cosmas28 requested changes

2019-02-13 15:38 UTC, cosmas28 commented on src/components/NavBar/NavBar.test.jsx
> +    let enzymeWrapper;
This variable name is not descriptive enough, I would prefer a name like `wrapper` or `componentWrapper`. What do you think?

2019-02-13 15:38 UTC, cosmas28 commented on src/components/NavBar/NavBar.test.jsx
> +describe('Navigation Bar :', () => {
The describe block title is not intuitive enough, what do you think about `The NavBar`? Also, the colon is not necessary.

2019-02-13 15:38 UTC, cosmas28 commented on src/components/NavBar/NavBar.test.jsx
> +        expect(enzymeWrapper).not.toBe(undefined);
any reason why you are not using snapshot testing here?

2019-02-13 15:46 UTC, cosmas28 commented on src/components/NavBar/NavBar.test.jsx
> +        expect(enzymeWrapper).not.toBe(undefined);
To fix the `Travis issues` please modify the `script:` in `.travis.yml` from `npm test` to `npm test -- -u`. You should also gitignore the snapshot files.

2019-02-13 16:34 UTC, cosmas28 requested changes

2019-02-13 16:34 UTC, cosmas28 commented on src/App.jsx
> +    <div>
What do you think about using `<React.Fragment>` instead of empty divs?

2019-02-13 16:34 UTC, cosmas28 commented on src/components/NavBar/index.jsx
> +                <NavLink to="/login">Login</NavLink>
Thess links are not working on browser, kindly create a `Bug` type story to configure the routes to enable us to use `Link` component from `react-router-dom`.

2019-02-15 06:10 UTC, Georgeygigz commented
> The head of your commit messages is the same, in such its advisable to have one commit message. So, please stash your commit messages.
@cosmas28  I have only have only two commits

2019-02-15 06:21 UTC, Georgeygigz commented on src/components/NavBar/NavBar.test.jsx
> +        expect(enzymeWrapper).not.toBe(undefined);
> any reason why you are not using snapshot testing here?

I will work on that too

2019-02-15 14:14 UTC, cosmas28 approved these changes

2019-02-15 14:20 UTC, merged